spring:
  application:
    name: test
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://10.81.1.17:5432/cim
      username: postgres
      password: postgres
  servlet:
    multipart:
      #支持的最大文件
      max-file-size: 100MB
      #文件请求的最大限制
      max-request-size: 100MB
server:
  port: 6001
  servlet:
    context-path: /mlgbb


